In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import math

In [ ]:
class EMALGO:
  def __init__(self,n,nsamples,probs,cluster_probs,max_iterations,threshold):
    self.noofsamples = nsamples
    self.probs = probs
    self.cluster_probs = cluster_probs
    self.generated_samples =None
    self.n = n
    self.max_iterations = max_iterations
    self.threshold = threshold
    self.stores = None
  def sample(self):
    k = len(self.probs)
    binomial_points = []
    for i in range(len(self.probs)):
        p = int(self.cluster_probs[i] * self.noofsamples)
        bin_points = np.random.binomial(self.n, self.probs[i], p)
        for j in bin_points:
            binomial_points.append(j)
    binomial_points = np.random.permutation(binomial_points)
    final_binomial_points = np.array(binomial_points)
    self.generated_samples = final_binomial_points
    return final_binomial_points
  def calcf_x(self,pc,xi):
    return (pc ** xi) * ((1 - pc) ** (self.n - xi)) * math.comb(self.n, xi)
  def EM(self):
    initialize_cluster_probs = np.ones(len(self.probs))/len(self.probs)
    initialize_probs = np.random.rand(len(self.probs))
    initialize_gammas = np.zeros((len(self.generated_samples),len(self.probs)))
    iterations = self.max_iterations
    while (iterations>=0):
      storeprobs = initialize_probs.copy()
      storeclusters = initialize_cluster_probs.copy()
      for j in range(len(self.generated_samples)):
        likelihoods = [(initialize_cluster_probs[i]*self.calcf_x(initialize_probs[i],self.generated_samples[j])) for i in range(len(self.probs))]
        initialize_gammas[j] = likelihoods/np.sum(likelihoods)
      for k in range(len(self.probs)):
            initialize_probs[k] = np.sum(initialize_gammas[:, k] * self.generated_samples) / np.sum(initialize_gammas[:, k] * self.n)
      initialize_cluster_probs = np.mean(initialize_gammas,axis=0)
      if np.max(np.abs(storeprobs-initialize_probs))<self.threshold and np.max(np.abs(storeclusters-initialize_cluster_probs))<self.threshold:
        del storeprobs,storeclusters
        break
      else:
        del storeprobs,storeclusters
      iterations-=1
    self.stores = [initialize_probs,initialize_cluster_probs]
    return initialize_probs,initialize_cluster_probs


In [ ]:
binomial_model = EMALGO(10,10000,[0.1,0.3,0.5,0.7,0.9],[0.2,0.4,0.1,0.2,0.1],max_iterations=100000,threshold=1e-4)

In [ ]:
binomial_model

In [ ]:
binomial_model.sample()

array([3, 2, 1, ..., 6, 9, 4])

In [ ]:
probs,cluster_probs = binomial_model.EM()

In [ ]:
probs

array([0.38354908, 0.12505185, 0.88880613, 0.33133495, 0.68393001])

In [ ]:
cluster_probs

array([0.16763989, 0.27124645, 0.1165546 , 0.24240192, 0.20215713])